version: '3'
services:
  app:
    build: ./docker/app
    volumes:
      - ./:/var/www
    ports:
      - 9000:9000
    stdin_open: true
    tty: true
  nginx:
    build: ./docker/nginx
    ports:
      - 9090:80
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
