version: '3'
services:
  app:
    build: ./docker/app
    volumes:
      - ./:/var/www
    ports:
      - 9000:9000
  nginx:
    build: ./docker/nginx
    ports:
      - 9090:80
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./:/var/www
    depends_on:
      - app
